language: node_js

services:
  - docker

node_js: "8"

install:
  - yarn

jobs:
  include:
    - stage: test
      script:
        - >-
          yarn stylelint
          && yarn test
          && yarn build-dev-css
          && yarn build-storybook

    - stage: deploy storybook
      script:
        - >- yarn build-storybook
          && ./deploy-storybook.sh
      if: branch = master AND NOT tag IS present

    - stage: build library and deploy
      script:
        - yarn build-lib
      before_deploy:
        - ls -1
      deploy:
        - provider: npm
          email: ujovlado+npm@rekurzia.sk
          api_key:
            secure: R31snMEOWrfbuJb0sn6Q+XbaFF7sEDZ0CO8mvHx9zZg9YvcBug7DgL61KzTg1n99IuRZAKhAzAjbAoqoinLmyhooRsj6PP4bqdJRLlDn7xvz7DyJL3UoLYw3vS+XspSWpbeQyUvKAaDpVwQEIKFnwZyuQnd7Cr/HANsoKLzinq6+xUrxLazCTXxz3lKHbh+/8770nWtRCczxPhO8nh+09022qSehvqdEBkMwmWccohvToXJv5cQFL1Fvo1Ox9Wj/KHARDLsy3bDSa4mRBXyEV1QskLMr8naiQ61EOFOysytvChQvd8X+AkcLf7lpAfYpZ+E1eEigA/x+OIoYRLPn/+vbvSqXcZPExe9vEXahZ7cEiVoqle8bghCJItppavgJ0O0R0sEWBGBGjTNfvm2gzXJ5aDPVuA1gNh5QyNDAQf8Wjxqe1mZOgAWoyYETeQPuWMvaakhKDkvQvkBsKsoiNLWAGI6Eqv1/IEnuwLQ30FRGnUaSrNHRqAmwBc0MKbZIR4czG4Qq+X/3f7c49YcbDks8gEEhh579GYblAV7mQVU40umJzjvuy1km2VmvHhDKJSXoBoNQauTrh/VZXNpxzqH54mr0Bp4nzil/Jkl29WNa1fCa30R4w4RtxkneS5qLLy8AXEdsDLFo4inKU5bC21b9U/xs6syhjlrBbQD4xh0=
          skip_cleanup: true
          on:
            tags: true
            repo: keboola/indigo-ui
            branch: master
      if: tag IS present

cache: yarn

notifications:
  slack:
    secure: bqtrl1M5N41BnT8LaL03mn13BJu6gYypUk7F+M373RS8xnJfCE6iGnI/uM+7dM1XQ/p5GOb4IrXX7TSGK8LH4IN06XmHkVparE7tTcJeHGszTV5bWoCPwPWOZjbBpjb8BaDoGo1KeJXLSdCimDWTxc4N9Dq9hAauv1bvXQfj4Clv9S56ib5YJdJ1PE8FqEQ/yfagYv8sr7rx0FaOp5hC9f2Scjmvpqz87WEhxNuO1tQsUGv98Iis+L+ZcyXYKfl4kDsHxzIF2SbQftZeFT5/ulocxYF7Je79qNtQsVB/FaelxQAtqvva30c+yjXYx7IIpQdX2+biFBvLI2Hohohl3Z9xxxo+1HGNlQYV/SmM5YIpgmcjv0YJRCp/bppq/YriwEQQ9tYkdvh0aFAjZWJSTFDAvo69Up9mxHBC9/NEWbnWZGK9078sf1KLY7yNcNOESdy1NhYGSGY4tqcXZ+GJ4BMJvLW9eE388FZ+lD3Vz3VgS5uKKWS5m1LHFo4O/YiqTpoUeAZPBt2MX4LTe38Ce87Uiekp3j4kPJGjIMu90Ox0fp7A6YHWArPR4VRjF5+Ii/Q9aYIp+JMzVMVI+dqgYGTP9wzmI94KwgSH5pqxOjNp4s8xMpv2PJ4m8AX6EQoAL6W4fzniRM80G7b7iYOvGnV09bHmjzGP2K7NONSfzhM=
  email: false
