language: node_js

node_js: "7"

install:
  - yarn

script:
  - yarn build-storybook

cache: yarn

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: indigo-ui-site-services-indigouis3-5izu6yd9zfix
  local-dir: build
  on:
    tags: true
    repo: keboola/indigo-ui
