language: node_js

services:
  - docker

node_js: "7"

install:
  - yarn

script:
  - yarn build-css
  - yarn build-storybook
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then ./deploy-storybook.sh; fi'
  - 'if [ "$TRAVIS_BRANCH" = "$TRAVIS_TAG" ]; then yarn build-dist-css; fi'

cache: yarn

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: indigo-ui-assets
    local_dir: revision
    upload-dir: indigo-ui
    skip_cleanup: true
    acl: public_read
    cache_control: 'max-age=31536000'
    detect_encoding: true
    on:
      tags: true
      repo: keboola/indigo-ui
      branch: kbc-bootstrap

  - provider: npm
    email: ujovlado+npm@rekurzia.sk
    api_key:
      secure: R31snMEOWrfbuJb0sn6Q+XbaFF7sEDZ0CO8mvHx9zZg9YvcBug7DgL61KzTg1n99IuRZAKhAzAjbAoqoinLmyhooRsj6PP4bqdJRLlDn7xvz7DyJL3UoLYw3vS+XspSWpbeQyUvKAaDpVwQEIKFnwZyuQnd7Cr/HANsoKLzinq6+xUrxLazCTXxz3lKHbh+/8770nWtRCczxPhO8nh+09022qSehvqdEBkMwmWccohvToXJv5cQFL1Fvo1Ox9Wj/KHARDLsy3bDSa4mRBXyEV1QskLMr8naiQ61EOFOysytvChQvd8X+AkcLf7lpAfYpZ+E1eEigA/x+OIoYRLPn/+vbvSqXcZPExe9vEXahZ7cEiVoqle8bghCJItppavgJ0O0R0sEWBGBGjTNfvm2gzXJ5aDPVuA1gNh5QyNDAQf8Wjxqe1mZOgAWoyYETeQPuWMvaakhKDkvQvkBsKsoiNLWAGI6Eqv1/IEnuwLQ30FRGnUaSrNHRqAmwBc0MKbZIR4czG4Qq+X/3f7c49YcbDks8gEEhh579GYblAV7mQVU40umJzjvuy1km2VmvHhDKJSXoBoNQauTrh/VZXNpxzqH54mr0Bp4nzil/Jkl29WNa1fCa30R4w4RtxkneS5qLLy8AXEdsDLFo4inKU5bC21b9U/xs6syhjlrBbQD4xh0=
    on:
      tags: true
      repo: keboola/indigo-ui
      branch: kbc-bootstrap

notifications:
  slack:
    secure: JRncm8bFlfqNDC8DPUJruaE9nqCU33RTOEJoaCkpnbkBAy+whvBCOExsJjj949j6MUgs/ltNizjhNzeBo+PSM8N/YVR6oyj1usBeLANJf/YifCRsTmfcA/DvrCvFRqrDPv7VucTcRfdh9ZeeDfa2zvT8O7nhgHWbL7crWAh/2AAlD5zhD/Ad+5urdQLTD/x1zoESfnEVuhUjvWPoF7dPNFpwQOyMqaSlH3w/MG+11Tu7h9847KBAQGMMSEFjkRSWBTasty65c4gmwmVDfkUWHBjwBKJIpONQij5gDIyowx3FIkNbyirw9TI2hEXhYIqTLJ8LMPcsiV8WtLkRGnDETPmp5/n6e6BRG5dFVO9QDmux0qH/dJzAZeBHKxK/NyhU2lQzrP6/51D6M4sylEclkbwSD42lXfHvsLL7F9YLgR4dr9yjVxu94NgPcKUXuC2H4/shCi8hQ89CR7mY8Y59yMBR5q/mpEA2IucKQ+4UjmZKQ9GGLbvS8Hjt2bEvT2fyA6pDOApT/lurPiez1KuR8ZfUXDszugOVdVZfThZsWgqZUPAHUkxGzHW7Advyj1ZmXK5oH36N9urwnXRfN0BCXsiOwu0THR41pmrTtlgmB3JQUCcMFEV2O5JEJB8QFdpD4A7LXt28G+KXp2uK82qjFd8KBDyWRtN4X/YxgZdv/Pk=
  email: false
