language: node_js

services:
  - docker

node_js: "7"

install:
  - yarn

script:
  - yarn build-css
  - yarn build-storybook
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then ./deploy-storybook.sh; fi'
  - 'if [ "$TRAVIS_BRANCH" = "$TRAVIS_TAG" ]; then yarn build-dist-css; fi'

cache: yarn

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: indigo.keboola.com
    local_dir: revision
    upload-dir: dist
    skip_cleanup: true
    acl: public_read
    on:
      tags: true
