language: node_js

services:
  - docker

node_js: "7"

install:
  - yarn

script:
  - yarn run build-css
  - yarn build-storybook
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then ./deploy-storybook.sh; fi'

cache: yarn

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: indigo.keboola.com
    local_dir: build
    skip_cleanup: true
    acl: public_read
    on:
      tags: true
      repo: keboola/indigo-ui
