language: node_js
node_js: "7"
branches:
  only:
    - master
script:
 - yarn deploy-storybook
deploy:
- provider: s3
  access_key_id: nevim
  secret_access_key:
    secure: nevim
  bucket: indigo-ui-site-services-indigouis3-5izu6yd9zfix