language: node_js

node_js: "7"

install:
  - yarn

script:
  - yarn run build-css
  - yarn build-storybook
  - grunt build prepare-revision

cache: yarn

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: indigo.keboola.com
    local_dir: build
    skip_cleanup: true
    acl: public_read
    on:
      tags: true
      repo: keboola/indigo-ui
