language: node_js

services:
  - docker

node_js: "8"

install:
  - yarn

jobs:
  include:
    - stage: test
      script:
        - >-
          yarn stylelint
          && yarn test
          && yarn build-dev-css
          && yarn build-storybook

    - stage: deploy storybook
      script:
        - >-
          yarn build-storybook
          && ./deploy-storybook.sh
      if: branch = master AND NOT tag IS present

    - stage: build library and deploy
      script:
        - yarn build-lib
      before_deploy:
        - ls -1
      deploy:
        - provider: npm
          email: ujovlado+npm@rekurzia.sk
          api_key:
            secure: R31snMEOWrfbuJb0sn6Q+XbaFF7sEDZ0CO8mvHx9zZg9YvcBug7DgL61KzTg1n99IuRZAKhAzAjbAoqoinLmyhooRsj6PP4bqdJRLlDn7xvz7DyJL3UoLYw3vS+XspSWpbeQyUvKAaDpVwQEIKFnwZyuQnd7Cr/HANsoKLzinq6+xUrxLazCTXxz3lKHbh+/8770nWtRCczxPhO8nh+09022qSehvqdEBkMwmWccohvToXJv5cQFL1Fvo1Ox9Wj/KHARDLsy3bDSa4mRBXyEV1QskLMr8naiQ61EOFOysytvChQvd8X+AkcLf7lpAfYpZ+E1eEigA/x+OIoYRLPn/+vbvSqXcZPExe9vEXahZ7cEiVoqle8bghCJItppavgJ0O0R0sEWBGBGjTNfvm2gzXJ5aDPVuA1gNh5QyNDAQf8Wjxqe1mZOgAWoyYETeQPuWMvaakhKDkvQvkBsKsoiNLWAGI6Eqv1/IEnuwLQ30FRGnUaSrNHRqAmwBc0MKbZIR4czG4Qq+X/3f7c49YcbDks8gEEhh579GYblAV7mQVU40umJzjvuy1km2VmvHhDKJSXoBoNQauTrh/VZXNpxzqH54mr0Bp4nzil/Jkl29WNa1fCa30R4w4RtxkneS5qLLy8AXEdsDLFo4inKU5bC21b9U/xs6syhjlrBbQD4xh0=
          skip_cleanup: true
      if: tag IS present

cache: yarn

notifications:
  slack:
    secure: Y3EKCFrnGFfT+ntkTkETnVkCzC1p1E8er6QagLd6zP87d5vh+SxDLruWeExMSmVWf9uTTTuEQJcEc4zPXfMoxYwu70moDMuJrO3x1FPJbiXbv3e8jX7R1M/rYGpGbATUhoyfc0ifcQf/ug6EupvA9GTwMX3iU8UejlgO3G0qDAdLks5DbCGQjBtEO281/KovRXLYEnw+Yv0pusHEaPrBrnuZN3HM2XXOzv6CXRaQ5TJM2BnGSfBZ7w1Kp0ym/D4zhZKrPorIkqni7/LPV4/Qi2g5zxtLjmtRRccaWr6cDXpZh27qN5CKy9B9qJjrQAkitwuc0XOWNXpnupUj01koqRAHJIKEsRYjNq2w6gSv1kVWUfQErKL0q7PQc7AGGv/BuM88/fZRnFrNglOvFsfjZB2Aee2bcoFG4eOCckC3ufrTn5tBc2nuhdpj2H/YCcGusyDF+pjH2hsexT4dpGbo7lkajfAkrf2OnjeLZjCrE+TpDh9KNzPTv4nEt1JkcU1BQnIsyOJCBGZF8H63yQq+rkevftwFVOPBEsUPpbG4L6O+fnshsM9X2LNJahu0dHnK+lFO1lp2l7DKSDiSyhkjXa7Fc7plp01DON3w1Ph1kFDJYCHfuDsPo1HMBOWhQ3b8WbtO2PiqrNwx6QAQh5g6DAwh+eMOmZ1LcOLstJtM/Oo=
  email: false
