version: "2"

services:

  node:
    build: .
    ports:
      - "9009:9009"
      - "35729:35729"
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
    command: sh -c 'yarn && yarn run storybook'

  aws:
    image: quay.io/keboola/aws-cli
    tty: true
    volumes:
      - ./:/code
    working_dir: /code

  https-proxy:
    image: nginx
    volumes:
      - ./.dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.dev/certs:/etc/nginx/ssl
    ports:
      - "9010:443"
    links:
      - node
