version: "2"

services:

  node:
    build: .
    ports:
      - "9009:9009"
      - "35729:35729"
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
    command: sh -c 'yarn && yarn run storybook'

  aws:
    image: quay.io/keboola/aws-cli
    tty: true
    volumes:
      - ./:/code
    working_dir: /code
