// Autogenerated file. Check svg-react-transformer.config.js
import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';

const Copy = ({ className, ...props }) => (
  <svg
    width="32"
    height="32"
    viewBox="0 0 15 17"
    className={classNames('icon', className)}
    {...props}
  >
    <path
      d="M10.5 0h-9C.675 0 0 .675 0 1.5V12h1.5V1.5h9V0zm2.25 3H4.5C3.675 3 3 3.675 3 4.5V15c0 .825.675 1.5 1.5 1.5h8.25c.825 0 1.5-.675 1.5-1.5V4.5c0-.825-.675-1.5-1.5-1.5zm0 12H4.5V4.5h8.25V15z"
      fill="currentColor"
      fillRule="evenodd"
    />
  </svg>
);

Copy.propTypes = {
  className: PropTypes.string,
};

export default Copy;
