// Autogenerated file. Check svg-react-transformer.config.js
import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';

const Duration = ({ className, ...props }) => (
  <svg
    width="32"
    height="32"
    viewBox="0 0 9 15"
    className={classNames('icon', className)}
    {...props}
  >
    <path
      d="M0 0v4.5h.007L0 4.508 3 7.5l-3 3 .007.008H0V15h9v-4.492h-.007L9 10.5l-3-3 3-2.992-.007-.008H9V0H0zm7.5 10.875V13.5h-6v-2.625l3-3 3 3zm-3-3.75l-3-3V1.5h6v2.625l-3 3z"
      fill="currentColor"
      fillRule="evenodd"
    />
  </svg>
);

Duration.propTypes = {
  className: PropTypes.string,
};

export default Duration;
