// Autogenerated file. Check generate-icons-index.js
import Application from './Application';
import ArrowDown from './ArrowDown';
import ArrowVertical from './ArrowVertical';
import Calendar from './Calendar';
import Check from './Check';
import Cloud from './Cloud';
import CloudDownload from './CloudDownload';
import Copy from './Copy';
import Danger from './Danger';
import DragHandle from './DragHandle';
import Duration from './Duration';
import Edit from './Edit';
import Error from './Error';
import Extractor from './Extractor';
import ExtractorTo from './ExtractorTo';
import Help from './Help';
import Jobs from './Jobs';
import Keboola from './Keboola';
import MappingIn from './MappingIn';
import MappingOut from './MappingOut';
import Minus from './Minus';
import Notification from './Notification';
import Options from './Options';
import Orchestration from './Orchestration';
import Overview from './Overview';
import Plus from './Plus';
import Refresh from './Refresh';
import Reset from './Reset';
import Run from './Run';
import Sandbox from './Sandbox';
import Search from './Search';
import SqlDep from './SqlDep';
import Storage from './Storage';
import SupportBy from './SupportBy';
import SupportChat from './SupportChat';
import SwitchOff from './SwitchOff';
import SwitchOn from './SwitchOn';
import Times from './Times';
import Transformation from './Transformation';
import TransformationAlt from './TransformationAlt';
import TransformationOverview from './TransformationOverview';
import Trash from './Trash';
import User from './User';
import Warning from './Warning';
import Writer from './Writer';

const Icon = {
  Application,
  ArrowDown,
  ArrowVertical,
  Calendar,
  Check,
  Cloud,
  CloudDownload,
  Copy,
  Danger,
  DragHandle,
  Duration,
  Edit,
  Error,
  Extractor,
  ExtractorTo,
  Help,
  Jobs,
  Keboola,
  MappingIn,
  MappingOut,
  Minus,
  Notification,
  Options,
  Orchestration,
  Overview,
  Plus,
  Refresh,
  Reset,
  Run,
  Sandbox,
  Search,
  SqlDep,
  Storage,
  SupportBy,
  SupportChat,
  SwitchOff,
  SwitchOn,
  Times,
  Transformation,
  TransformationAlt,
  TransformationOverview,
  Trash,
  User,
  Warning,
  Writer,
};
export default Icon;
