// Autogenerated file. Check svg-react-transformer.config.js
import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';

const Options = ({ className, ...props }) => {
  return (
    <svg
      width="32"
      height="32"
      viewBox="0 0 19 19"
      className={classNames('icon', className)}
      {...props}
    >
      <path
        d="M16.465 10.248c.038-.299.067-.597.067-.915 0-.317-.029-.616-.067-.914l2.024-1.54a.462.462 0 0 0 .115-.598l-1.919-3.229a.489.489 0 0 0-.585-.205l-2.39.933a7.06 7.06 0 0 0-1.62-.915L11.724.392a.464.464 0 0 0-.47-.392H7.415a.464.464 0 0 0-.47.392l-.364 2.473a7.424 7.424 0 0 0-1.622.915l-2.39-.933a.474.474 0 0 0-.584.205l-1.92 3.23a.452.452 0 0 0 .116.597l2.024 1.54a7.203 7.203 0 0 0-.067.914c0 .308.029.616.067.915l-2.024 1.54a.462.462 0 0 0-.115.597l1.919 3.23c.115.205.374.28.585.205l2.39-.933a7.06 7.06 0 0 0 1.62.914l.365 2.474c.029.224.23.392.47.392h3.838c.24 0 .442-.168.47-.392l.365-2.474a7.424 7.424 0 0 0 1.622-.914l2.389.933c.22.084.47 0 .585-.205l1.92-3.23a.462.462 0 0 0-.116-.597l-2.024-1.54zM9.333 12a2.67 2.67 0 0 1-2.666-2.667 2.67 2.67 0 0 1 2.666-2.666A2.67 2.67 0 0 1 12 9.333 2.67 2.67 0 0 1 9.333 12z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
};

Options.propTypes = {
  className: PropTypes.string,
};

export default Options;
