// Autogenerated file. Check svg-react-transformer.config.js
import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';

const Refresh = ({ className, ...props }) => (
  <svg
    width="32"
    height="32"
    viewBox="0 0 12 12"
    className={classNames('icon', className)}
    {...props}
  >
    <path
      d="M10.23 1.763A5.968 5.968 0 0 0 5.993 0 5.992 5.992 0 0 0 0 6c0 3.315 2.678 6 5.993 6a5.987 5.987 0 0 0 5.797-4.5h-1.56a4.493 4.493 0 0 1-4.237 3 4.504 4.504 0 0 1-4.5-4.5c0-2.482 2.017-4.5 4.5-4.5 1.245 0 2.355.518 3.165 1.335L6.743 5.25h5.25V0L10.23 1.763z"
      fill="currentColor"
      fillRule="evenodd"
    />
  </svg>
);

Refresh.propTypes = {
  className: PropTypes.string,
};

export default Refresh;
