// Autogenerated file. Check svg-react-transformer.config.js
import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';

const User = ({ className, ...props }) => {
  return (
    <svg
      width="32"
      height="32"
      viewBox="0 0 16 16"
      className={classNames('icon', className)}
      {...props}
    >
      <path
        d="M4.44 7.17c.3 1.76 1.712 3.5 3.56 3.5s3.259-1.74 3.56-3.5a1.19 1.19 0 0 0 .662-1.07c0-.289-.1-.568-.283-.79.076-.332.115-.67.115-1.01a4.061 4.061 0 1 0-8.108 0c0 .34.038.678.115 1.01a1.238 1.238 0 0 0-.283.79 1.19 1.19 0 0 0 .662 1.07zm11.37 6.82a11.726 11.726 0 0 0-5.135-2.58.523.523 0 0 0-.213-.05h-.17a.489.489 0 0 0-.234.06 5.493 5.493 0 0 1-4.115 0 .488.488 0 0 0-.235-.06h-.124c-.037 0-.075.01-.112.01a11.818 11.818 0 0 0-5.283 2.62.531.531 0 0 0-.189.41v1.05a.55.55 0 0 0 .545.55h14.91a.55.55 0 0 0 .545-.55V14.4a.53.53 0 0 0-.189-.41h-.001z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  );
};

User.propTypes = {
  className: PropTypes.string
};

export default User;
